db: 
  host: localhost
  database: favbot
  username: user_name
  password: xxxxxxxxx
  adapter: mysql

twitter: 
  consumer_key: SmrSHrkB3xAABCOv9Av1A
  consumer_secret: NVppoonw8jWVEtVQkyfSCeyBqEYCZh1L6KJHfkg19S0
